services:
  - type: web
    name: gitaru-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://sirisia.netlify.app
      - key: MAX_DOWNLOAD_SIZE
        value: 500MB
      - key: YTDLP_PATH
        value: /usr/local/bin/yt-dlp
